steps:
  - name: gcr.io/cloud-builders/docker
    id: Tag and push image
    entrypoint: sh
    args:
      - -c
      - |
        docker build --build-arg CADDY_IMAGE=$_CADDY_IMAGE -t $_APP_IMAGE:$SHORT_SHA .
        docker push $_APP_IMAGE:$SHORT_SHA
  - name: gcr.io/cloud-builders/gke-deploy
    id: Deploy to GKE
    args:
      - run
      - --filename=deployment.yaml
      - --image=$_APP_IMAGE:$SHORT_SHA
      - --location=$_ZONE
      - --cluster=$_CLUSTER
