steps:
  - name: gcr.io/cloud-builders/docker
    id: Tag and push image
    entrypoint: sh
    args:
      - -c
      - |
        docker build --build-arg CADDY_IMAGE=$_CADDY_IMAGE -t $_APP_IMAGE:$SHORT_SHA .
        docker push $_APP_IMAGE:$SHORT_SHA
  - id: Prep SSH for GitHub
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "$$SECRET_KEY" >> /root/.ssh/id_ed25519 && chmod 400 /root/.ssh/id_ed25519
        ssh-keyscan -p 2022 source.developers.google.com > /root/.ssh/known_hosts
    secretEnv:
      - SECRET_KEY
    volumes:
      - name: ssh
        path: /root/.ssh
  - id: Update manifests
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        (
          set -e
          AUTHOR_NAME=$$(git log -1 --pretty=format:"%an")
          AUTHOR_EMAIL=$$(git log -1 --pretty=format:"%ae")
          LAST_COMMIT_MESSAGE=$$(git log --format=%B -n 1 $SHORT_SHA)
          mkdir tmp && git clone $_CONFIG_REPO tmp && cd tmp && \
          sed "s/COMMIT_SHA/$SHORT_SHA/g" master/deployment.yaml.tpl > master/deployment.yaml && \
          git add master/deployment.yaml && \
          git config user.name "$$AUTHOR_NAME" && \
          git config user.email "$$AUTHOR_EMAIL" && \
          git commit -m "$$LAST_COMMIT_MESSAGE" && \
          git push origin master
        ) || true
    volumes:
      - name: ssh
        path: /root/.ssh
availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT/secrets/$_SECRET_KEY/versions/latest
      env: SECRET_KEY