steps:
  - name: gcr.io/cloud-builders/docker
    id: Build and push App image
    entrypoint: sh
    args:
      - -c
      - |
        docker build --build-arg caddy_image=$_CADDY_IMAGE -t $_APP_IMAGE .
        docker push $_APP_IMAGE
  - name: gcr.io/cloud-builders/gcloud
    id: Update Cloud Run service
    entrypoint: sh
    args:
      - -c
      - |
        gcloud run services update $_SERVICE --platform=managed --image=$_APP_IMAGE --region=$_REGION --async
