apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: default
  labels:
    app: plausible
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plausible
  template:
    metadata:
      labels:
        app: plausible
    spec:
      containers:
      - name: plausible
        image: us-central1-docker.pkg.dev/mechapower/apps/plausible
        resources:
          limits:
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 6Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15