apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: default
  labels:
    app: plausible
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plausible
  template:
    metadata:
      labels:
        app: plausible
    spec:
      containers:
      - name: plausible
        image: us-central1-docker.pkg.dev/mechapower/apps/plausible
        resources:
          limits:
            memory: 24Mi
          requests:
            cpu: 10m
            memory: 8Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: plausible
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "plausible-dyrri2j"}}}'
spec:
  type: ClusterIP
  selector:
    app: plausible
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80