apiVersion: v1
kind: Service
metadata:
  name: plausible
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "plausible-dyrri2j"}}}'
spec:
  type: ClusterIP
  selector:
    app: plausible
  ports:
    - name: caddy
      protocol: TCP
      port: 80
      targetPort: 80